default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails_apz_dev

test:
  <<: *default
  database: rails_apz_dev

production:
  <<: *default
  database: rails_apz_dev
